Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -141,16 +141,11 @@ jobs:
             exit $?
         fi
         git tag $remote_rev
-        # echo "Push"
-        # git push origin $remote_rev
-        # if [ $? -ne 0 ]; then
-        #     echo "Failed to push code. Exit $?"
-        #     exit $?
-        # fi
-        # echo "Done."
-        # exit 0
-    - name: Push changes
-      uses: ad-m/github-push-action@master
-      with:
-        github_token: ${{ secrets.ACCESS_TOKEN }}
-        repository: NationsTechCoreLib/${{ matrix.target }}
+        echo "Push"
+        git push origin $remote_rev
+        if [ $? -ne 0 ]; then
+            echo "Failed to push code. Exit $?"
+            exit $?
+        fi
+        echo "Done."
+        exit 0
